from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def create_report(data, filename="career_report.pdf"):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    # Title
    elements.append(
        Paragraph(
            "CareerNavigator Report",
            styles["Title"]
        )
    )

    elements.append(Spacer(1, 20))

    # ATS Score
    elements.append(
        Paragraph(
            "ATS Score",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"{data.get('atsScore', 'N/A')} / 100",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 12))

    # Summary
    elements.append(
        Paragraph(
            "Profile Summary",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            data.get("summary", "No summary available"),
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 12))

    # Recommended Roles
    elements.append(
        Paragraph(
            "Recommended Roles",
            styles["Heading2"]
        )
    )

    roles = data.get("recommendedRoles", [])

    if roles:
        for role in roles:
            elements.append(
                Paragraph(
                    f"• {role.get('role')} ({role.get('score')}%)",
                    styles["Normal"]
                )
            )
    else:
        elements.append(
            Paragraph(
                "No roles found",
                styles["Normal"]
            )
        )

    elements.append(Spacer(1, 12))

    # Skills
    elements.append(
        Paragraph(
            "Skills",
            styles["Heading2"]
        )
    )

    skills = data.get("skills", [])

    if skills:
        elements.append(
            Paragraph(
                ", ".join(skills),
                styles["Normal"]
            )
        )
    else:
        elements.append(
            Paragraph(
                "No skills found",
                styles["Normal"]
            )
        )

    elements.append(Spacer(1, 12))

    # Strengths
    elements.append(
        Paragraph(
            "Strengths",
            styles["Heading2"]
        )
    )

    strengths = data.get("strengths", [])

    if strengths:
        for item in strengths:
            elements.append(
                Paragraph(
                    f"• {item}",
                    styles["Normal"]
                )
            )

    elements.append(Spacer(1, 12))

    # Weaknesses
    elements.append(
        Paragraph(
            "Weaknesses",
            styles["Heading2"]
        )
    )

    weaknesses = data.get("weaknesses", [])

    if weaknesses:
        for item in weaknesses:
            elements.append(
                Paragraph(
                    f"• {item}",
                    styles["Normal"]
                )
            )

    elements.append(Spacer(1, 12))

    # Missing Skills
    elements.append(
        Paragraph(
            "Missing Skills",
            styles["Heading2"]
        )
    )

    missing_skills = data.get("missingSkills", [])

    if missing_skills:
        for item in missing_skills:
            elements.append(
                Paragraph(
                    f"• {item}",
                    styles["Normal"]
                )
            )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "Generated by AI Career Navigator",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return filename